server:
  port: 8082
spring:
  application:
    name: spring-cloud-eureka-client-sample
  cloud:
    inetutils:
      preferred-networks[0]: 192.168
eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster.mmt.com/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true